### PR TITLE
Update Roots.jl version bound

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by mschauer** [comment]
Is it working locally?

**Comment by oschulz** [comment]
~~Roots doesn't actually seem to be used - I took it out now, tests pass.~~

**Comment by oschulz** [comment]
> ~~Roots doesn't actually seem to be used - I took it out now, tests pass.~~

Ah, my bad - it is used, but only for a high number of dims.

**Comment by oschulz** [comment]
> Is it working locally?

Just checked @mschauer, seems to be fine  :

```julia
(GoldenSequences) pkg> st Roots
  ...
  [f2b01f46] Roots v2.0.1

julia> GoldenSequences.Phi(200)
1.0034630832855487
```
```

**Comment by oschulz** [comment]
Thanks @mschauer ! Can you start the package registrator on [#76efe44](https://github.com/mschauer/GoldenSequences.jl/commit/76efe44a98e553b6e331e3e9e62e3ceea4761c76) ?

**Comment by mschauer** [comment]
This is already registered!

**Comment by oschulz** [comment]
> This is already registered!

Ooops, sorrry - I had looked for an open General PR, but it had already been merged. :-)

**Pull request merged**
